# Generated by Django 2.2.2 on 2022-03-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagemodel',
            name='in_effect',
            field=models.BooleanField(default=True),
        ),
    ]
