# Generated by Django 2.2.2 on 2022-03-17 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio_name', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('marker_icon', models.ImageField(null=True, upload_to='studio/marker')),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('profile_image', models.ImageField(null=True, upload_to='studio/profile')),
                ('cover_image', models.ImageField(null=True, upload_to='studio/cover')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studio_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
