# Generated by Django 2.2.16 on 2022-04-05 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_studiorating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiorating',
            name='stars',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
